### ISSUE TITLE
Issue with executing the jar

### ISSUE THREAD

**Issue by allthingssecurity** [startup-palace/swsg#1]
./sbt "run --help" gives the below error

root@instance-1:~/swsg# ./sbt "run --help"
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /root/swsg/project
[info] Loading settings from build.sbt ...
[info] Set current project to SWSG (in build file:/root/swsg/)
[success] Total time: 2 s, completed Aug 19, 2019 9:00:34 AM
[info] Packaging /root/swsg/target/scala-2.12/swsg_2.12-0.1.0-SNAPSHOT.jar ...
[info] Done packaging.
[error] java.lang.RuntimeException: No main class detected.
[error]         at scala.sys.package$.error(package.scala:27)
[error]         at sbt.Defaults$.$anonfun$bgRunTask$4(Defaults.scala:1179)
[error]         at scala.Option.getOrElse(Option.scala:121)
[error]         at sbt.Defaults$.$anonfun$bgRunTask$3(Defaults.scala:1179)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:66)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:263)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:272)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:263)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (Compile / bgRun) No main class detected.
[error] Total time: 0 s, completed Aug 19, 2019 9:00:34 AM

Can you please advice

**Comment by allthingssecurity** [comment]
Worked so closing it
